require "./test/fast_config_yaml_aliases.rb"
require "./test/fast_config_test.rb"
require "./test/fast_config_with_env_test.rb"
ENV['FAST_CONFIG_DIR']="test/test_config"
require "./test/fast_config_config_dir_setting_test.rb"
